### ISSUE TITLE
Left the logger on any chance in toggle it off?

### ISSUE THREAD

**Issue by SGZ-Creations** [madmanbeavisx/Zero2HeroPlusMinus-Unheard#2]
![image](https://github.com/user-attachments/assets/18c9f60e-a9c1-4a65-923c-8e505c6367fb)
![image](https://github.com/user-attachments/assets/8e51590f-8f94-4cd5-9332-6d996c946f98)
![image](https://github.com/user-attachments/assets/65c93080-1716-4e76-bb06-d5d62dbbbf8d)

**Comment by madmanbeavisx** [comment]
This is fixed.
I was not putting the LogTextcolor in a couple of the logging messages.

**Comment by SGZ-Creations** [comment]
ty
